import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import 'yansi_personalization.dart';
import 'yansi_action_execution_guard.dart';

enum YansiActionRisk { safe, confirm }
enum YansiActionType { prioritizeTasks, reviewReminders, analyzeSpending, activateGoal, predictHousehold }
class YansiActionProposal {final YansiActionType type;final YansiActionRisk risk;final String title;final String explanation;final Map<String,dynamic> data;const YansiActionProposal({required this.type,required this.risk,required this.title,required this.explanation,this.data=const {}});}
class YansiActionResult {final bool completed;final bool needsConfirmation;final String message;final Map<String,dynamic> data;const YansiActionResult({required this.completed,required this.needsConfirmation,required this.message,this.data=const {}});}

class YansiActionOrchestrator {
 final SharedPreferences prefs; const YansiActionOrchestrator({required this.prefs});
 YansiActionProposal proposal(String action,{Map<String,dynamic> data=const {}}){switch(action.toUpperCase()){case 'PRIORITIZE':return YansiActionProposal(type:YansiActionType.prioritizeTasks,risk:YansiActionRisk.safe,title:'Prioritize today',explanation:'Rank open tasks using urgency and existing LifeOS context.',data:data);case 'REVIEW':return YansiActionProposal(type:YansiActionType.reviewReminders,risk:YansiActionRisk.safe,title:'Review upcoming events',explanation:'Bring the most relevant reminders into focus.',data:data);case 'ANALYZE':return YansiActionProposal(type:YansiActionType.analyzeSpending,risk:YansiActionRisk.safe,title:'Analyze money pattern',explanation:'Compare recent spending and identify the main driver of change.',data:data);case 'ACTIVATE':return YansiActionProposal(type:YansiActionType.activateGoal,risk:YansiActionRisk.safe,title:'Activate a goal',explanation:'Turn a drifting goal into one small actionable step.',data:data);default:return YansiActionProposal(type:YansiActionType.predictHousehold,risk:YansiActionRisk.safe,title:'Predict household needs',explanation:'Use recurring purchase history to prepare a suggested list.',data:data);}}
 Future<YansiActionResult> execute(YansiActionProposal p,{bool confirmed=false})async{final guard=const YansiActionExecutionGuard();final guardAction=_guardAction(p.type);if(!guard.canExecute(action:guardAction,confirmed:confirmed)){await _pending(p);return YansiActionResult(completed:false,needsConfirmation:true,message:guard.explanation(guardAction));}final personalization=YansiPersonalization(prefs:prefs);if(p.risk==YansiActionRisk.confirm&&!confirmed){await _pending(p);return const YansiActionResult(completed:false,needsConfirmation:true,message:'I prepared the action, but I need your confirmation before I execute it.');}await prefs.setString('yansi_last_action',jsonEncode({'type':p.type.name,'title':p.title,'at':DateTime.now().toIso8601String()}));try{late YansiActionResult r;switch(p.type){case YansiActionType.prioritizeTasks:final tasks=_records('yansi_tasks');tasks.sort((a,b)=>_priority(b).compareTo(_priority(a)));await _save('yansi_tasks',tasks.take(100).toList());r=YansiActionResult(completed:true,needsConfirmation:false,message:'I prioritized your open tasks. Your highest-priority items are ready to review.',data:{'count':tasks.length});break;case YansiActionType.reviewReminders:await prefs.setString('yansi_focus_mode','calendar');r=const YansiActionResult(completed:true,needsConfirmation:false,message:'I focused LifeOS on the reminders that need attention next.');break;case YansiActionType.analyzeSpending:await prefs.setString('yansi_focus_mode','money');r=const YansiActionResult(completed:true,needsConfirmation:false,message:'I focused LifeOS on money intelligence so Yansi can explain the spending change.');break;case YansiActionType.activateGoal:await prefs.setString('yansi_focus_mode','goals');r=const YansiActionResult(completed:true,needsConfirmation:false,message:'I activated goals intelligence so the next useful step can be identified.');break;case YansiActionType.predictHousehold:await prefs.setString('yansi_focus_mode','household');r=const YansiActionResult(completed:true,needsConfirmation:false,message:'I prepared household intelligence for recurring needs.');break;}await personalization.recordOutcome(action:p.type.name,success:r.completed);return r;}catch(e){await personalization.recordOutcome(action:p.type.name,success:false);return YansiActionResult(completed:false,needsConfirmation:false,message:'I could not complete that action safely.',data:{'error':'action_failed'});}}
 String _guardAction(YansiActionType type){switch(type){case YansiActionType.prioritizeTasks:return 'prioritize_tasks';case YansiActionType.reviewReminders:return 'review_reminders';case YansiActionType.analyzeSpending:return 'analyze_spending';case YansiActionType.activateGoal:return 'activate_goal';case YansiActionType.predictHousehold:return 'predict_household';}}
 Future<YansiActionResult> confirmPending()async{final raw=prefs.getString('yansi_pending_action');if(raw==null)return const YansiActionResult(completed:false,needsConfirmation:false,message:'There is no pending Yansi action.');try{final m=jsonDecode(raw)as Map;final type=YansiActionType.values.firstWhere((v)=>v.name=='${m['type']}');final p=YansiActionProposal(type:type,risk:YansiActionRisk.confirm,title:'${m['title']??'Pending action'}',explanation:'${m['explanation']??''}',data:Map<String,dynamic>.from((m['data'] as Map?)??{}));final result=await execute(p,confirmed:true);await prefs.remove('yansi_pending_action');return result;}catch(_){return const YansiActionResult(completed:false,needsConfirmation:false,message:'I could not safely restore that pending action.');}}
 Future<void> cancelPending()async=>prefs.remove('yansi_pending_action');bool get hasPending=>prefs.containsKey('yansi_pending_action');Future<void> _pending(YansiActionProposal p)async=>prefs.setString('yansi_pending_action',jsonEncode({'type':p.type.name,'title':p.title,'explanation':p.explanation,'data':p.data,'createdAt':DateTime.now().toIso8601String()}));int _priority(Map<String,dynamic> t){if(t['priority'] is num)return(t['priority']as num).toInt();final s='${t['urgency']??''}'.toLowerCase();if(s.contains('high')||s.contains('urgent'))return 3;if(s.contains('medium'))return 2;return 1;}List<Map<String,dynamic>> _records(String key){final raw=prefs.getStringList(key)??const<String>[];return raw.map((v){try{return Map<String,dynamic>.from(jsonDecode(v)as Map);}catch(_){return <String,dynamic>{};}}).where((e)=>e.isNotEmpty).toList();}Future<void> _save(String key,List<Map<String,dynamic>> records)async=>prefs.setStringList(key,records.map(jsonEncode).toList());
}
