const layers=[['01','Outer Skin','Flexible recycled-compatible elastomer','impact'],['02','Energy Lattice','Cellular structure that manages impact energy','impact'],['03','Thermal Cocoon','Spreads and buffers short heat peaks','thermal'],['04','Floating Core','Shock-isolated electronics architecture','core'],['05','Smart Sensor Strap','Protected power + data + sensing interface','sensor'],['06','Yansi Core','Safety, context and intelligent orchestration','ai']];
const list=document.querySelector('#layers'),watch=document.querySelector('#watch'),readout=document.querySelector('#readout'),impact=document.querySelector('#impact'),thermalState=document.querySelector('#thermalState');
layers.forEach(([n,t,d,type])=>{const el=document.createElement('button');el.className='layer';el.dataset.type=type;el.innerHTML=`<b>${n} · ${t}</b><span>${d}</span>`;el.addEventListener('click',()=>focusLayer(type,t,el));list.appendChild(el)});
function focusLayer(type,title,el){document.querySelectorAll('.layer').forEach(x=>x.classList.remove('active'));el.classList.add('active');watch.dataset.focus=type;readout.textContent=title;impact.textContent=type==='impact'?'ABSORB':'READY';thermalState.textContent=type==='thermal'?'FLOW':'BALANCED'}
document.querySelector('[data-action="explode"]').onclick=()=>{watch.classList.add('exploded');readout.textContent='Architecture separated for inspection'};
document.querySelector('[data-action="reset"]').onclick=()=>{watch.classList.remove('exploded','thermal');watch.dataset.focus='';readout.textContent='Energy Cocoon ready';impact.textContent='ABSORB';thermalState.textContent='BALANCED';document.querySelectorAll('.layer').forEach(x=>x.classList.remove('active'))};
document.querySelector('[data-action="thermal"]').onclick=()=>{watch.classList.toggle('thermal');const on=watch.classList.contains('thermal');readout.textContent=on?'Thermal path: core → spreader → outer air':'Thermal flow hidden';thermalState.textContent=on?'FLOW':'BALANCED'};
document.querySelector('#mode').onclick=()=>{const b=document.querySelector('#mode'),y=b.textContent==='ENERGY COCOON';b.textContent=y?'YANSI INTELLIGENCE':'ENERGY COCOON';document.body.classList.toggle('yansi',y);readout.textContent=y?'Yansi intelligence layer engaged':'Energy Cocoon architecture engaged'};
const c=document.querySelector('#space'),x=c.getContext('2d');let w=0,h=0,dpr=1;function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;x.setTransform(dpr,0,0,dpr,0,0)}resize();addEventListener('resize',resize);
const stars=Array.from({length:180},()=>({x:Math.random(),y:Math.random(),r:.2+Math.random()*1.3,a:.15+Math.random()*.6,s:.0002+Math.random()*.0007}));
function draw(t){x.clearRect(0,0,w,h);for(const s of stars){s.y=(s.y+s.s)%1;x.globalAlpha=s.a;x.fillStyle='#72eaff';x.beginPath();x.arc(s.x*w,s.y*h,s.r,0,Math.PI*2);x.fill()}x.globalAlpha=.08;x.strokeStyle='#25dfff';for(let i=0;i<4;i++){x.beginPath();x.arc(w*.72,h*.5,180+i*70+t*.002*(i+1),0,Math.PI*2);x.stroke()}requestAnimationFrame(draw)}requestAnimationFrame(draw);
addEventListener('pointermove',e=>{watch.style.setProperty('--mx',e.clientX/innerWidth-.5);watch.style.setProperty('--my',e.clientY/innerHeight-.5)});