/* AllInMyDay Studio — first-principles realtime 3D scene engine. */
(()=>{
const host=document.querySelector('.stage');if(!host)return;const old=document.querySelector('#studio-engine');if(old)old.remove();
const canvas=document.createElement('canvas');canvas.id='studio-engine';canvas.setAttribute('aria-label','AllInMyDay realtime 3D viewport');host.appendChild(canvas);
const gl=canvas.getContext('webgl2',{antialias:true,alpha:true})||canvas.getContext('webgl',{antialias:true,alpha:true});if(!gl){host.dataset.webgl='unsupported';return;}
const vs='attribute vec3 p;attribute vec3 n;uniform mat4 mvp;uniform mat4 model;varying vec3 N;varying vec3 P;void main(){N=mat3(model)*n;P=(model*vec4(p,1.0)).xyz;gl_Position=mvp*vec4(p,1.0);}';
const fs='precision mediump float;uniform vec3 base;uniform vec3 light;uniform float glow;varying vec3 N;varying vec3 P;void main(){vec3 nn=normalize(N),l=normalize(light-P);float d=max(dot(nn,l),0.0);float rim=pow(1.0-max(dot(nn,normalize(-P)),0.0),2.0);vec3 c=base*(.2+.8*d)+vec3(.02,.35,.45)*rim*glow;gl_FragColor=vec4(c,1.0);}';
function shader(t,s){const q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q}
const prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,vs));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);gl.useProgram(prog);
const loc={p:gl.getAttribLocation(prog,'p'),n:gl.getAttribLocation(prog,'n'),mvp:gl.getUniformLocation(prog,'mvp'),model:gl.getUniformLocation(prog,'model'),base:gl.getUniformLocation(prog,'base'),light:gl.getUniformLocation(prog,'light'),glow:gl.getUniformLocation(prog,'glow')};
function cube(){const v=[[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1],[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1]],f=[[0,1,2,3,0,0,1],[5,4,7,6,0,0,-1],[3,2,6,7,0,1,0],[4,5,1,0,0,-1,0],[1,5,6,2,1,0,0],[4,0,3,7,-1,0,0]],d=[],i=[];f.forEach(a=>{for(let k=0;k<4;k++){const p=v[a[k]];d.push(...p,a[4],a[5],a[6])}});for(let q=0;q<6;q++){const b=q*4;i.push(b,b+1,b+2,b,b+2,b+3)}return{d,i}}
function sphere(){const d=[],i=[],R=16,C=24;for(let y=0;y<=R;y++){const v=y/R*Math.PI;for(let x=0;x<=C;x++){const u=x/C*Math.PI*2,s=Math.sin(v),p=[s*Math.cos(u),Math.cos(v),s*Math.sin(u)];d.push(...p,...p)}}for(let y=0;y<R;y++)for(let x=0;x<C;x++){const a=y*(C+1)+x,b=a+C+1;i.push(a,b,a+1,b,b+1,a+1)}return{d,i}}
function cylinder(){const d=[],i=[],C=32;for(let y=0;y<=1;y++)for(let x=0;x<=C;x++){const u=x/C*Math.PI*2,p=[Math.cos(u),y*2-1,Math.sin(u)];d.push(...p,Math.cos(u),0,Math.sin(u))}for(let y=0;y<1;y++)for(let x=0;x<C;x++){const a=y*(C+1)+x,b=a+C+1;i.push(a,b,a+1,b,b+1,a+1)}return{d,i}}
const meshes={primitive:cube(),core:cube(),cocoon:sphere(),strap:cylinder(),product:cylinder(),text:cube(),transform:cube(),group:cube(),duplicate:cube(),import:cube()};
const buffers={};Object.keys(meshes).forEach(k=>{const m=meshes[k],vb=gl.createBuffer(),ib=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(m.d),gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(m.i),gl.STATIC_DRAW);buffers[k]={vb,ib,count:m.i.length}});gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];function mul(a,b){const o=new Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}function tr(x,y,z){const m=I();m[12]=x;m[13]=y;m[14]=z;return m}function sc(x,y,z){const m=I();m[0]=x;m[5]=y;m[10]=z;return m}function rx(a){const c=Math.cos(a),s=Math.sin(a),m=I();m[5]=c;m[6]=s;m[9]=-s;m[10]=c;return m}function ry(a){const c=Math.cos(a),s=Math.sin(a),m=I();m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m}function rz(a){const c=Math.cos(a),s=Math.sin(a),m=I();m[0]=c;m[1]=s;m[4]=-s;m[5]=c;return m}function persp(f,a,n,z){const q=1/Math.tan(f/2),m=new Array(16).fill(0);m[0]=q/a;m[5]=q;m[10]=(z+n)/(n-z);m[11]=-1;m[14]=2*z*n/(n-z);return m}
const state={objects:[{id:1,type:'core',x:0,y:0,z:0,rx:.12,ry:.45,rz:-.08,sx:1.25,sy:1.6,sz:.7,selected:true}],selected:1,camera:{yaw:.45,pitch:.15,distance:6},light:[3,4,5],material:'Adaptive TPU Cocoon'};
function resize(){const r=host.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';gl.viewport(0,0,canvas.width,canvas.height)}resize();addEventListener('resize',resize);
function model(o){return mul(tr(o.x,o.y,o.z),mul(rz(o.rz),mul(ry(o.ry),mul(rx(o.rx),sc(o.sx,o.sy,o.sz)))))}
function draw(){gl.clearColor(.005,.012,.02,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const asp=canvas.width/canvas.height;let view=mul(ry(-state.camera.yaw),rx(-state.camera.pitch));view=mul(tr(0,0,-state.camera.distance),view);const vp=mul(persp(Math.PI/4,asp,.1,100),view);state.objects.forEach(o=>{const b=buffers[o.type]||buffers.primitive,mm=model(o);gl.bindBuffer(gl.ARRAY_BUFFER,b.vb);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,b.ib);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(loc.n);gl.vertexAttribPointer(loc.n,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(loc.model,false,new Float32Array(mm));gl.uniformMatrix4fv(loc.mvp,false,new Float32Array(mul(vp,mm)));const hot=o.selected?1:0;gl.uniform3f(loc.base,.035+.045*hot,.22+.2*hot,.30+.22*hot);gl.uniform3f(loc.light,...state.light);gl.uniform1f(loc.glow,o.selected?1.6:.45);gl.drawElements(gl.TRIANGLES,b.count,gl.UNSIGNED_SHORT,0)});requestAnimationFrame(draw)}requestAnimationFrame(draw);
function sync(){window.dispatchEvent(new CustomEvent('studio-scene-change',{detail:state}))}
window.AllInMyDayStudioEngine={state,add(type){const id=Date.now();state.objects.forEach(o=>o.selected=false);state.objects.push({id,type:type in meshes?type:'primitive',x:0,y:0,z:0,rx:0,ry:0,rz:0,sx:1,sy:1,sz:1,selected:true});state.selected=id;sync();return id},select(id){const n=state.objects.find(o=>o.id===id);if(!n)return;state.objects.forEach(o=>o.selected=false);n.selected=true;state.selected=id;sync()},update(id,patch){const n=state.objects.find(o=>o.id===id);if(!n)return;Object.assign(n,patch);sync()},duplicate(){const o=state.objects.find(x=>x.id===state.selected);if(!o)return;const n={...o,id:Date.now(),x:o.x+.6,y:o.y+.25,selected:true};state.objects.forEach(x=>x.selected=false);state.objects.push(n);state.selected=n.id;sync()},remove(){if(state.objects.length<=1)return;state.objects=state.objects.filter(x=>x.id!==state.selected);state.selected=state.objects.at(-1).id;state.objects.at(-1).selected=true;sync()},rotate(dx,dy){state.camera.yaw+=dx;state.camera.pitch=Math.max(-1.2,Math.min(1.2,state.camera.pitch+dy));sync()},setMaterial(m){state.material=m;sync()},export(){return JSON.stringify(state,null,2)}};
let down=false,lx=0,ly=0;canvas.addEventListener('pointerdown',e=>{down=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!down)return;state.camera.yaw+=(e.clientX-lx)*.008;state.camera.pitch=Math.max(-1.2,Math.min(1.2,state.camera.pitch+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY});['pointerup','pointercancel'].forEach(n=>canvas.addEventListener(n,()=>down=false));canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.distance=Math.max(2.5,Math.min(12,state.camera.distance+e.deltaY*.006))},{passive:false});
})();
