/* AllInMyDay Studio: first-principles WebGL scene engine. No external 3D editor dependency. */
(()=>{
 const host=document.querySelector('.stage');if(!host)return; const old=document.querySelector('#studio-engine');if(old)old.remove();
 const canvas=document.createElement('canvas');canvas.id='studio-engine';canvas.setAttribute('aria-label','AllInMyDay realtime 3D viewport');host.appendChild(canvas);
 const gl=canvas.getContext('webgl2',{antialias:true,alpha:true})||canvas.getContext('webgl',{antialias:true,alpha:true});if(!gl){host.dataset.webgl='unsupported';return;}
 const vs='attribute vec3 p;attribute vec3 n;uniform mat4 mvp;uniform mat4 model;varying vec3 vN;varying vec3 vP;void main(){vN=mat3(model)*n;vP=(model*vec4(p,1.0)).xyz;gl_Position=mvp*vec4(p,1.0);}';
 const fs='precision mediump float;uniform vec3 base;uniform vec3 light;uniform float glow;varying vec3 vN;varying vec3 vP;void main(){vec3 N=normalize(vN);vec3 L=normalize(light-vP);float d=max(dot(N,L),0.0);float rim=pow(1.0-max(dot(N,normalize(-vP)),0.0),2.0);vec3 c=base*(.22+.78*d)+vec3(.02,.35,.45)*rim*glow;gl_FragColor=vec4(c,1.0);}';
 function shader(t,s){const q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q;}
 const prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,vs));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);gl.useProgram(prog);
 const loc={p:gl.getAttribLocation(prog,'p'),n:gl.getAttribLocation(prog,'n'),mvp:gl.getUniformLocation(prog,'mvp'),model:gl.getUniformLocation(prog,'model'),base:gl.getUniformLocation(prog,'base'),light:gl.getUniformLocation(prog,'light'),glow:gl.getUniformLocation(prog,'glow')};
 const verts=[[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1],[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1]],faces=[[0,1,2,3,0,0,1],[5,4,7,6,0,0,-1],[3,2,6,7,0,1,0],[4,5,1,0,0,-1,0],[1,5,6,2,1,0,0],[4,0,3,7,-1,0,0]],data=[],idx=[];faces.forEach(f=>{for(let i=0;i<4;i++){const v=verts[f[i]];data.push(v[0],v[1],v[2],f[4],f[5],f[6]);}});for(let f=0;f<6;f++){const b=f*4;idx.push(b,b+1,b+2,b,b+2,b+3);}
 const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(idx),gl.STATIC_DRAW);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(loc.n);gl.vertexAttribPointer(loc.n,3,gl.FLOAT,false,24,12);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);
 const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];function mul(a,b){const o=new Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}function trans(x,y,z){const m=I();m[12]=x;m[13]=y;m[14]=z;return m;}function scale(x,y,z){const m=I();m[0]=x;m[5]=y;m[10]=z;return m;}function rx(a){const c=Math.cos(a),s=Math.sin(a),m=I();m[5]=c;m[6]=s;m[9]=-s;m[10]=c;return m;}function ry(a){const c=Math.cos(a),s=Math.sin(a),m=I();m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m;}function rz(a){const c=Math.cos(a),s=Math.sin(a),m=I();m[0]=c;m[1]=s;m[4]=-s;m[5]=c;return m;}function persp(fov,asp,n,f){const q=1/Math.tan(fov/2),m=new Array(16).fill(0);m[0]=q/asp;m[5]=q;m[10]=(f+n)/(n-f);m[11]=-1;m[14]=2*f*n/(n-f);return m;}
 const state={objects:[{id:1,type:'core',x:0,y:0,z:0,rx:.12,ry:.45,rz:-.08,sx:1.25,sy:1.6,sz:.7,selected:true}],selected:1,camera:{yaw:.45,pitch:.15,distance:6},light:[3,4,5]};
 function resize(){const r=host.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';gl.viewport(0,0,canvas.width,canvas.height);}resize();addEventListener('resize',resize);
 function model(o){return mul(trans(o.x,o.y,o.z),mul(rz(o.rz),mul(ry(o.ry),mul(rx(o.rx),scale(o.sx,o.sy,o.sz)))));}
 function draw(){gl.clearColor(.005,.012,.02,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const asp=canvas.width/canvas.height;let view=mul(ry(-state.camera.yaw),rx(-state.camera.pitch));view=mul(trans(0,0,-state.camera.distance),view);const vp=mul(persp(Math.PI/4,asp,.1,100),view);state.objects.forEach(o=>{const mm=model(o);gl.uniformMatrix4fv(loc.model,false,new Float32Array(mm));gl.uniformMatrix4fv(loc.mvp,false,new Float32Array(mul(vp,mm)));gl.uniform3f(loc.base,o.selected?.08:.035,o.selected?.42:.22,o.selected?.52:.30);gl.uniform3f(loc.light,...state.light);gl.uniform1f(loc.glow,o.selected?1.5:.5);gl.drawElements(gl.TRIANGLES,idx.length,gl.UNSIGNED_SHORT,0);});requestAnimationFrame(draw);}requestAnimationFrame(draw);
 function sync(){window.dispatchEvent(new CustomEvent('studio-scene-change',{detail:state}));}
 window.AllInMyDayStudioEngine={state,add(type){const id=Date.now();state.objects.forEach(o=>o.selected=false);state.objects.push({id,type,x:0,y:0,z:0,rx:0,ry:0,rz:0,sx:1,sy:1,sz:1,selected:true});state.selected=id;sync();return id;},duplicate(){const o=state.objects.find(x=>x.id===state.selected);if(!o)return;const n={...o,id:Date.now(),x:o.x+.5,y:o.y+.25,selected:true};state.objects.forEach(x=>x.selected=false);state.objects.push(n);state.selected=n.id;sync();},remove(){if(state.objects.length<=1)return;state.objects=state.objects.filter(x=>x.id!==state.selected);state.selected=state.objects.at(-1).id;state.objects.at(-1).selected=true;sync();},rotate(dx,dy){state.camera.yaw+=dx;state.camera.pitch=Math.max(-1.2,Math.min(1.2,state.camera.pitch+dy));sync();},export(){return JSON.stringify(state,null,2);}};
 let down=false,lx=0,ly=0;canvas.addEventListener('pointerdown',e=>{down=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!down)return;state.camera.yaw+=(e.clientX-lx)*.008;state.camera.pitch=Math.max(-1.2,Math.min(1.2,state.camera.pitch+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY;});['pointerup','pointercancel'].forEach(n=>canvas.addEventListener(n,()=>down=false));canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.distance=Math.max(2.5,Math.min(12,state.camera.distance+e.deltaY*.006));},{passive:false});
})();
