import 'dart:async';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LifeOZMasterShell extends StatefulWidget {
  final SharedPreferences prefs;
  const LifeOZMasterShell({super.key, required this.prefs});
  @override State<LifeOZMasterShell> createState() => _LifeOZMasterShellState();
}

class _LifeOZMasterShellState extends State<LifeOZMasterShell> with SingleTickerProviderStateMixin {
  late final AnimationController motion;
  final FlutterTts tts = FlutterTts();
  Timer? timer;
  String name = '';
  bool splash = true;
  int active = -1;
  int reality = 0;
  double yaw = 0;
  double pitch = 0;
  static const colors = <Color>[Color(0xFF20D9FF),Color(0xFF48F0A0),Color(0xFF9C70FF),Color(0xFF62E7FF),Color(0xFFFF67D4),Color(0xFF9B9BFF)];
  static const cores = <Color>[Color(0xFF42F5A7),Color(0xFFFFB14A),Color(0xFFB66BFF),Color(0xFF42DFFF),Color(0xFFD968FF)];
  static const realms = <String>['OREON PRIME','TERRA FLUX','VORTEX NEXUS','CRYSTA LUMEN','NEBULA SOUL','SHADOW CORE'];
  static const messages = <String>['Life intelligence is ready.','Growth intelligence is ready.','Productivity intelligence is ready.','Time intelligence is ready.','Future intelligence is ready.'];

  double alpha(bool condition,double yes,double no) => condition ? yes : no;

  @override void initState(){super.initState();name=widget.prefs.getString('user_name')??'';motion=AnimationController(vsync:this,duration:const Duration(seconds:16))..repeat();tts.setSpeechRate(.44);timer=Timer(const Duration(milliseconds:1600),(){if(mounted)setState(()=>splash=false);});}
  @override void dispose(){timer?.cancel();motion.dispose();tts.stop();super.dispose();}
  Future<void> speak(String text)async{await tts.stop();await tts.speak(text);}

  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFF01040A),body:SafeArea(child:AnimatedBuilder(animation:motion,builder:(_,__)=>Stack(fit:StackFit.expand,children:<Widget>[CustomPaint(painter:SpacePainter(motion.value,reality)),splash?_splash():_home()]))));

  Widget _splash()=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:<Widget>[SizedBox(width:210,height:210,child:CustomPaint(painter:YansiPainter(motion.value,colors[reality],yaw,pitch,true))),const SizedBox(height:14),const Text('LifeOZ',style:TextStyle(color:Colors.white,fontSize:34,fontWeight:FontWeight.w900,letterSpacing:5)),const SizedBox(height:7),const Text('INITIALIZING LIVING INTELLIGENCE',style:TextStyle(color:Color(0xFF63E8FF),fontSize:9,letterSpacing:1.7))]));

  Widget _home()=>LayoutBuilder(builder:(_,box){final w=box.maxWidth;final h=box.maxHeight;final center=Offset(w/2,h*.46);final size=math.min(w*.70,330.0);final nodes=<Offset>[Offset(w*.50,h*.14),Offset(w*.16,h*.30),Offset(w*.84,h*.30),Offset(w*.17,h*.70),Offset(w*.83,h*.70)];final color=colors[reality];return Stack(children:<Widget>[
    Positioned(top:12,left:18,right:18,child:Row(children:<Widget>[SizedBox(width:44,height:44,child:CustomPaint(painter:LogoPainter(motion.value))),const SizedBox(width:9),const Text('LifeOZ',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900,letterSpacing:3)),const Spacer(),GestureDetector(onTap:_realities,child:Container(width:48,height:48,decoration:BoxDecoration(shape:BoxShape.circle,color:Colors.black.withValues(alpha:.3),border:Border.all(color:color.withValues(alpha:.65))),child:Icon(Icons.auto_awesome,color:color,size:24)))])),
    Positioned.fill(child:CustomPaint(painter:NetworkPainter(motion.value,nodes,center,active,color))),
    for(int i=0;i<nodes.length;i++) Positioned(left:nodes[i].dx-50,top:nodes[i].dy-50,child:GestureDetector(onTap:(){setState(()=>active=i);speak(messages[i]);},child:SizedBox(width:100,height:100,child:CustomPaint(painter:CorePainter(i,cores[i],motion.value,active==i))))),
    Positioned(left:center.dx-size/2,top:center.dy-size/2,child:GestureDetector(onPanUpdate:(d){setState((){yaw=(yaw+d.delta.dx*.008).clamp(-1.2,1.2);pitch=(pitch+d.delta.dy*.008).clamp(-.8,.8);});},onTap:()=>speak(name.isEmpty?'I am Yansi, your personal LifeOS intelligence.':'Welcome, $name. I am Yansi, your personal LifeOS intelligence.'),child:SizedBox(width:size,height:size,child:CustomPaint(painter:YansiPainter(motion.value,active<0?color:cores[active],yaw,pitch,true))))),
    Positioned(left:18,right:18,bottom:14,child:Row(children:<Widget>[Expanded(child:BottomButton(label:realms[reality],icon:Icons.auto_awesome,onTap:_realities)),const SizedBox(width:10),Expanded(child:BottomButton(label:'ROTATE YANSI',icon:Icons.threed_rotation,onTap:()=>setState(()=>yaw+=.45)))])),
  ]);});

  void _realities(){showModalBottomSheet<void>(context:context,backgroundColor:const Color(0xFF050B14),isScrollControlled:true,builder:(ctx)=>SafeArea(child:SizedBox(height:MediaQuery.of(ctx).size.height*.72,child:Column(children:<Widget>[const SizedBox(height:18),const Text('LIVING VISUAL REALITIES',style:TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w800,letterSpacing:2)),const SizedBox(height:5),const Text('Moving 3D worlds — not static images.',style:TextStyle(color:Color(0xFF6BEAFF),fontSize:9)),const SizedBox(height:14),Expanded(child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:realms.length,itemBuilder:(ctx,i){final c=colors[i];final selected=reality==i;return GestureDetector(onTap:(){setState(()=>reality=i);Navigator.pop(ctx);speak('${realms[i]} selected.');},child:Container(height:88,margin:const EdgeInsets.only(bottom:10),decoration:BoxDecoration(borderRadius:BorderRadius.circular(20),border:Border.all(color:c.withValues(alpha:alpha(selected,.85,.22)),width:alpha(selected,2,1)),gradient:LinearGradient(colors:<Color>[c.withValues(alpha:.14),Colors.black.withValues(alpha:.35)])),child:Row(children:<Widget>[SizedBox(width:76,height:76,child:CustomPaint(painter:YansiPainter(motion.value+i*.1,c,yaw,pitch,false))),const SizedBox(width:10),Expanded(child:Text(realms[i],style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800,letterSpacing:1))),Icon(selected?Icons.check_circle:Icons.arrow_forward_ios,color:c,size:alpha(selected,22,14))])));}))]))));}
}

class BottomButton extends StatelessWidget{final String label;final IconData icon;final VoidCallback onTap;const BottomButton({super.key,required this.label,required this.icon,required this.onTap});@override Widget build(BuildContext context)=>GestureDetector(onTap:onTap,child:Container(height:50,decoration:BoxDecoration(color:Colors.black.withValues(alpha:.34),borderRadius:BorderRadius.circular(25),border:Border.all(color:Colors.white.withValues(alpha:.1))),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:<Widget>[Icon(icon,color:const Color(0xFF6BEAFF),size:17),const SizedBox(width:7),Flexible(child:Text(label,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white70,fontSize:9,letterSpacing:1.1,fontWeight:FontWeight.w700)))])));}

class SpacePainter extends CustomPainter{final double phase;final int reality;SpacePainter(this.phase,this.reality);@override void paint(Canvas c,Size s){const b=<Color>[Color(0xFF061A2A),Color(0xFF071E16),Color(0xFF160A25),Color(0xFF061923),Color(0xFF190817),Color(0xFF03030A)];final rect=Offset.zero&s;c.drawRect(rect,Paint()..shader=RadialGradient(radius:1.15,colors:<Color>[b[reality],const Color(0xFF010207)]).createShader(rect));final r=math.Random(700+reality*17);for(int i=0;i<120;i++){final a=.02+.04*((math.sin(phase*math.pi*2+i)+1)/2);c.drawCircle(Offset(r.nextDouble()*s.width,r.nextDouble()*s.height),.4+r.nextDouble()*1.1,Paint()..color=Colors.white.withValues(alpha:a));}}@override bool shouldRepaint(covariant SpacePainter old)=>true;}

class NetworkPainter extends CustomPainter{final double phase;final List<Offset> nodes;final Offset center;final int active;final Color color;NetworkPainter(this.phase,this.nodes,this.center,this.active,this.color);@override void paint(Canvas c,Size s){final p=Paint()..style=PaintingStyle.stroke..strokeWidth=1..color=color.withValues(alpha:.13);for(final n in nodes){c.drawLine(center,n,p);final t=(phase+n.dx/s.width)%1;c.drawCircle(Offset.lerp(center,n,t)!,2,Paint()..color=color.withValues(alpha:.75));}c.drawCircle(center,44+7*math.sin(phase*math.pi*2),Paint()..style=PaintingStyle.stroke..strokeWidth=1.2..color=color.withValues(alpha:active>=0?.30:.14));}@override bool shouldRepaint(covariant NetworkPainter old)=>true;}

class LogoPainter extends CustomPainter{final double phase;LogoPainter(this.phase);@override void paint(Canvas c,Size s){final m=Offset(s.width/2,s.height/2);final r=s.width*.4;final p=Paint()..style=PaintingStyle.stroke..strokeWidth=1.8..color=const Color(0xFF20D9FF).withValues(alpha:.8);c.drawCircle(m,r,p);c.drawOval(Rect.fromCenter(center:m,width:r*1.55,height:r*.55),p);c.drawCircle(Offset(m.dx+math.cos(phase*math.pi*2)*r*.7,m.dy),2.8,Paint()..color=const Color(0xFF48F0A0));}@override bool shouldRepaint(covariant LogoPainter old)=>true;}

class CorePainter extends CustomPainter{final int index;final Color color;final double phase;final bool active;CorePainter(this.index,this.color,this.phase,this.active);@override void paint(Canvas c,Size s){final m=Offset(s.width/2,s.height/2);final r=28*(1+.06*math.sin(phase*math.pi*2+index));c.drawCircle(m,r*1.2,Paint()..color=color.withValues(alpha:active?.28:.12)..maskFilter=const MaskFilter.blur(BlurStyle.normal,16));c.drawCircle(m,r,Paint()..shader=RadialGradient(colors:<Color>[Colors.white.withValues(alpha:.85),color,Colors.black]).createShader(Rect.fromCircle(center:m,radius:r)));final p=Paint()..style=PaintingStyle.stroke..strokeWidth=active?2.2:1.1..color=color.withValues(alpha:active?.95:.55);for(int k=0;k<2;k++){c.save();c.translate(m.dx,m.dy);c.rotate(phase*math.pi*2*(k==0?1:-.7)+index);c.drawOval(Rect.fromCenter(center:Offset.zero,width:r*2.6,height:r*.72),p);c.restore();}}@override bool shouldRepaint(covariant CorePainter old)=>true;}

class YansiPainter extends CustomPainter{final double phase;final Color color;final double yaw;final double pitch;final bool large;YansiPainter(this.phase,this.color,this.yaw,this.pitch,this.large);Offset project(double x,double y,double z,double scale){final a=yaw+math.sin(phase*math.pi*2)*.3;final b=pitch+math.cos(phase*math.pi*2)*.15;final x1=x*math.cos(a)-z*math.sin(a);final z1=x*math.sin(a)+z*math.cos(a);final y1=y*math.cos(b)-z1*math.sin(b);final z2=y*math.sin(b)+z1*math.cos(b);final q=1/(1+z2*.42);return Offset(x1*q*scale,y1*q*scale);}@override void paint(Canvas c,Size s){final m=Offset(s.width/2,s.height/2);final scale=s.shortestSide*(large?.31:.36);final breath=1+.055*math.sin(phase*math.pi*2);c.drawCircle(m,scale*1.35*breath,Paint()..color=color.withValues(alpha:large?.16:.12)..maskFilter=MaskFilter.blur(BlurStyle.normal,large?28:13));c.drawCircle(m,scale*breath,Paint()..shader=RadialGradient(center:const Alignment(-.25,-.28),radius:1,colors:<Color>[Colors.white.withValues(alpha:.95),color.withValues(alpha:.9),color.withValues(alpha:.3),const Color(0xFF01040A)],stops:const <double>[0,.17,.58,1]).createShader(Rect.fromCircle(center:m,radius:scale)));final p=Paint()..style=PaintingStyle.stroke..strokeWidth=large?1:.65..color=color.withValues(alpha:.6);for(int i=0;i<7;i++){final lat=-1+i*(2/6);final y=lat*scale;final width=math.sqrt(math.max(0,1-lat*lat))*scale;c.save();c.translate(m.dx,m.dy+y*math.cos(pitch));c.rotate(phase*math.pi*2*(i.isEven?.55:-.4)+yaw);c.drawOval(Rect.fromCenter(center:Offset.zero,width:width*2,height:scale*.28),p);c.restore();}final rand=math.Random(92);final ps=<Particle>[];for(int i=0;i<(large?120:42);i++){final theta=rand.nextDouble()*math.pi*2;final phi=math.acos(2*rand.nextDouble()-1);final rad=.72+rand.nextDouble()*.36;var x=math.sin(phi)*math.cos(theta)*rad;final y=math.cos(phi)*rad;var z=math.sin(phi)*math.sin(theta)*rad;final spin=phase*math.pi*2*(.7+(i%5)*.08);final rx=x*math.cos(spin)-z*math.sin(spin);z=x*math.sin(spin)+z*math.cos(spin);x=rx;ps.add(Particle(project(x,y,z,scale),(1-z).clamp(.35,1.6),z));}ps.sort((a,b)=>a.z.compareTo(b.z));for(final p in ps){final rr=(.7+p.depth*(large?1.9:1.2)).clamp(.55,3.0);c.drawCircle(m+p.offset,rr,Paint()..color=Colors.white.withValues(alpha:(.18+p.depth*.35).clamp(.12,.75)));}for(int i=0;i<3;i++){final a=phase*math.pi*2*(1+i*.17)+i*2.1;final pos=m+project(math.cos(a)*1.18,math.sin(a*1.7)*.55,math.sin(a)*.85,scale);c.drawCircle(pos,2.2,Paint()..color=color);}c.drawCircle(m.translate(-scale*.25,-scale*.30),scale*.12,Paint()..color=Colors.white.withValues(alpha:.5));}@override bool shouldRepaint(covariant YansiPainter old)=>true;}
class Particle{final Offset offset;final double depth;final double z;Particle(this.offset,this.depth,this.z);}
