import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LifeOZReferenceHome extends StatefulWidget {
  final SharedPreferences prefs;
  const LifeOZReferenceHome({super.key, required this.prefs});
  @override State<LifeOZReferenceHome> createState()=>_LifeOZReferenceHomeState();
}
class _LifeOZReferenceHomeState extends State<LifeOZReferenceHome>{
 final FlutterTts _tts=FlutterTts(); String _name='';
 static const colors=[Color(0xFF55D98A),Color(0xFFFFB447),Color(0xFFD76BFF),Color(0xFF39D7FF),Color(0xFFB66CFF)];
 static const titles=['Life & Growth','Guardian & Care','Prosperity','Time & Commitments','Personal Intelligence'];
 @override void initState(){super.initState();_name=prefs.getString('user_name')??'';_tts.setSpeechRate(.44);}
 SharedPreferences get prefs=>widget.prefs;
 @override void dispose(){_tts.stop();super.dispose();}
 Future<void> speak(String s)async{await _tts.stop();await _tts.speak(s);}
 Future<void> profile()async{final c=TextEditingController(text:_name);final v=await showDialog<String>(context:context,builder:(d)=>AlertDialog(backgroundColor:const Color(0xFF07101B),title:const Text('PROFILE'),content:TextField(controller:c,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(labelText:'Name')),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(d,c.text.trim()),child:const Text('SAVE'))]));if(v!=null&&v.isNotEmpty){await prefs.setString('user_name',v);if(mounted)setState(()=>_name=v);}}
 void core(int i){final m=['Life, growth, goals and daily progress.','Household, care and protection commitments.','Expenses, savings, investments and money intelligence.','Calendar, bills, renewals and time-sensitive commitments.','Diary, personal goals, reflection and connected LifeOS context.'][i];speak('${titles[i]}. $m');showModalBottomSheet(context:context,backgroundColor:const Color(0xFF050C16),showDragHandle:true,builder:(_)=>Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(titles[i],style:const TextStyle(fontSize:22)),const SizedBox(height:12),Text(m,style:const TextStyle(color:Colors.white70)),const SizedBox(height:18),const Text('ONE SCREEN • ONE TAP • ONE REPORT',style:TextStyle(letterSpacing:2,fontSize:11,color:Colors.white54))])));}
 @override Widget build(BuildContext c){return Scaffold(backgroundColor:const Color(0xFF010207),body:SafeArea(child:Stack(children:[const Positioned.fill(child:CustomPaint(painter:SpacePainter())),Positioned(top:18,left:24,right:24,child:Row(children:[Container(width:58,height:58,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:const Color(0xFFFFC067),width:1.5)),child:const Icon(Icons.all_inclusive_rounded,color:Color(0xFFFFC067),size:34)),const SizedBox(width:14),const Text('LIFEOZ',style:TextStyle(fontSize:28,letterSpacing:5,fontWeight:FontWeight.w600)),const Spacer(),IconButton(onPressed:profile,icon:const Icon(Icons.tune_rounded),color:const Color(0xFFFFC067))])),Positioned.fill(top:100,bottom:55,child:GestureDetector(onTapUp:(e){final s=MediaQuery.sizeOf(c);final cen=Offset(s.width/2,s.height*.43);final dx=e.localPosition.dx-cen.dx,dy=e.localPosition.dy-cen.dy;final d=math.sqrt(dx*dx+dy*dy);if(d<125){speak(_name.isEmpty?'I am here.':'I am here, $_name.');}else if(d<300)core(nearest(math.atan2(dy,dx)));},child:const CustomPaint(painter:ConstellationPainter()))),Positioned(bottom:22,left:0,right:0,child:Center(child:Text(_name.isEmpty?'LIVING INTELLIGENCE':'LIVING INTELLIGENCE • $_name',style:const TextStyle(letterSpacing:4,fontSize:11,color:Colors.white70))))]));}
 int nearest(double a){const p=[-math.pi/2,0,math.pi/2,math.pi,2.5];var b=0,bd=99.0;for(var i=0;i<p.length;i++){var d=(a-p[i]).abs();if(d>math.pi)d=2*math.pi-d;if(d<bd){bd=d;b=i;}}return b;}
}
class SpacePainter extends CustomPainter{const SpacePainter();@override void paint(Canvas c,Size s){final p=Paint()..color=Colors.white.withValues(alpha:.3);final r=math.Random(17);for(var i=0;i<100;i++){c.drawCircle(Offset(r.nextDouble()*s.width,r.nextDouble()*s.height),1,p);}}@override bool shouldRepaint(covariant SpacePainter o)=>false;}
class ConstellationPainter extends CustomPainter{
 const ConstellationPainter();
 @override void paint(Canvas c,Size s){final o=Offset(s.width/2,s.height*.43),r=math.min(s.width*.29,170.0);final pts=[Offset(o.dx,o.dy-r*1.45),Offset(o.dx+r*1.28,o.dy-r*.3),Offset(o.dx+r*.92,o.dy+r*1.25),Offset(o.dx-r*.92,o.dy+r*1.25),Offset(o.dx-r*1.28,o.dy-r*.3)];final line=Paint()..style=PaintingStyle.stroke..strokeWidth=1..color=const Color(0xFF4F7185).withValues(alpha:.45);for(final p in pts)c.drawLine(o,p,line);final orbit=Paint()..style=PaintingStyle.stroke..color=const Color(0xFF6F91A4).withValues(alpha:.2);c.drawOval(Rect.fromLTRB(o.dx-r*1.6,o.dy-r*.65,o.dx+r*1.6,o.dy+r*.65),orbit);c.drawOval(Rect.fromLTRB(o.dx-r*1.35,o.dy-r*.45,o.dx+r*1.35,o.dy+r*.45),orbit);drawY(c,o,92);for(var i=0;i<5;i++)drawCore(c,pts[i],i,42);}
 void drawY(Canvas c,Offset o,double r){final g=Paint()..shader=RadialGradient(colors:[const Color(0xFF56E5FF).withValues(alpha:.85),const Color(0xFF4D72FF).withValues(alpha:.4),Colors.transparent]).createShader(Rect.fromCircle(center:o,radius:r*1.45));c.drawCircle(o,r*1.45,g);final f=Paint()..shader=const LinearGradient(colors:[Color(0xFF69F2FF),Color(0xFF4B9EFF),Color(0xFF7C55D9)]).createShader(Rect.fromCircle(center:o,radius:r));c.drawCircle(o,r,f);final e=Paint()..style=PaintingStyle.stroke..strokeWidth=2..color=const Color(0xFFBDEBFF);for(var i=0;i<3;i++){final h=r*(.35+i*.2);c.drawOval(Rect.fromLTRB(o.dx-r*.85,o.dy-h/2,o.dx+r*.85,o.dy+h/2),e);}}
 void drawCore(Canvas c,Offset o,int i,double r){final col=_LifeOZReferenceHomeState.colors[i];final g=Paint()..shader=RadialGradient(colors:[col.withValues(alpha:.75),col.withValues(alpha:.12),Colors.transparent]).createShader(Rect.fromCircle(center:o,radius:r*1.5));c.drawCircle(o,r*1.5,g);final q=Paint()..style=PaintingStyle.stroke..strokeWidth=2..color=col;c.drawOval(Rect.fromLTRB(o.dx-r,o.dy-r*.32,o.dx+r,o.dy+r*.32),q);c.save();c.translate(o.dx,o.dy);c.rotate(i*.42);c.drawOval(Rect.fromLTRB(-r,-r*.32,r,r*.32),q);c.restore();final ic=Paint()..style=PaintingStyle.stroke..strokeWidth=3..color=col;final path=Path();if(i==0||i==1){path.moveTo(o.dx,o.dy+r*.55);path.cubicTo(o.dx-r*.7,o.dy,o.dx-r*.4,o.dy-r*.8,o.dx,o.dy-r*.25);path.cubicTo(o.dx+r*.4,o.dy-r*.8,o.dx+r*.7,o.dy,o.dx,o.dy+r*.55);c.drawPath(path,ic);}else if(i==2){for(var k=0;k<24;k++){final a=k/23*math.pi*3;final rr=r*.6*(1-k/30);final p=Offset(o.dx+math.cos(a)*rr,o.dy+math.sin(a)*rr);if(k==0)path.moveTo(p.dx,p.dy);else path.lineTo(p.dx,p.dy);}c.drawPath(path,ic);}else if(i==3){c.drawCircle(o,r*.48,ic);c.drawLine(Offset(o.dx,o.dy),Offset(o.dx,o.dy-r*.3),ic);c.drawLine(Offset(o.dx,o.dy),Offset(o.dx+r*.24,o.dy+r*.18),ic);}else{path.moveTo(o.dx,o.dy-r*.65);path.lineTo(o.dx+r*.48,o.dy);path.lineTo(o.dx,o.dy+r*.65);path.lineTo(o.dx-r*.48,o.dy);path.close();c.drawPath(path,ic);}c.drawCircle(o,3.5,Paint()..color=Colors.white);}
 @override bool shouldRepaint(covariant ConstellationPainter o)=>false;
}
