import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LifeOZMasterReferenceHome extends StatefulWidget {
  final SharedPreferences prefs;
  const LifeOZMasterReferenceHome({super.key, required this.prefs});
  @override State<LifeOZMasterReferenceHome> createState()=>_LifeOZMasterReferenceHomeState();
}

class _LifeOZMasterReferenceHomeState extends State<LifeOZMasterReferenceHome>{
  final FlutterTts tts=FlutterTts(); String name='';
  static const colors=[Color(0xff58df8b),Color(0xffffa92f),Color(0xffd66aff),Color(0xff42d8ff),Color(0xffa96cff)];
  static const titles=['Life & Growth','Guardian & Care','Prosperity','Time & Commitments','Personal Intelligence'];
  @override void initState(){super.initState();name=widget.prefs.getString('user_name')??'';tts.setSpeechRate(.44);}
  @override void dispose(){tts.stop();super.dispose();}
  Future<void> speak(String s)async{await tts.stop();await tts.speak(s);}
  Future<void> profile()async{final c=TextEditingController(text:name);final v=await showDialog<String>(context:context,builder:(d)=>AlertDialog(backgroundColor:const Color(0xff07101c),title:const Text('PROFILE'),content:TextField(controller:c,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(labelText:'Name')),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(d,c.text.trim()),child:const Text('SAVE'))]));if(v!=null&&v.isNotEmpty){await widget.prefs.setString('user_name',v);if(mounted)setState(()=>name=v);}}
  void core(int i){final m=['Life, growth, goals and progress.','Care, household and protection.','Expenses, savings and investments.','Calendar, bills and commitments.','Diary, goals and personal intelligence.'][i];speak('${titles[i]}. $m');showModalBottomSheet(context:context,backgroundColor:const Color(0xff050b14),showDragHandle:true,builder:(_)=>Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(titles[i],style:const TextStyle(fontSize:22,fontWeight:FontWeight.w600)),const SizedBox(height:10),Text(m,style:const TextStyle(color:Colors.white70)),const SizedBox(height:16),const Text('ONE SCREEN • ONE TAP • ONE REPORT',style:TextStyle(letterSpacing:2,fontSize:10,color:Colors.white54)),const SizedBox(height:12)])));}
  @override Widget build(BuildContext context){return Scaffold(backgroundColor:const Color(0xff01030a),body:SafeArea(child:Stack(children:[const Positioned.fill(child:CustomPaint(painter:_Stars())),Positioned(top:14,left:22,right:22,child:Row(children:[const SizedBox(width:62,height:62,child:CustomPaint(painter:_Logo())),const SizedBox(width:12),const Text('LIFEOZ',style:TextStyle(fontSize:30,fontWeight:FontWeight.w600,letterSpacing:5)),const Spacer(),IconButton(onPressed:profile,icon:const Icon(Icons.tune_rounded),color:Color(0xffffb75b))])),Positioned.fill(top:76,child:LayoutBuilder(builder:(c,b){final center=Offset(b.maxWidth/2,b.maxHeight*.43);final r=math.min(b.maxWidth*.27,150.0);final pts=[Offset(center.dx,center.dy-r*1.52),Offset(center.dx+r*1.32,center.dy-r*.18),Offset(center.dx+r*.9,center.dy+r*1.22),Offset(center.dx-r*.9,center.dy+r*1.22),Offset(center.dx-r*1.32,center.dy-r*.18)];return GestureDetector(onTapUp:(d){var best=-1,bd=92.0;for(var i=0;i<5;i++){final dx=d.localPosition.dx-pts[i].dx,dy=d.localPosition.dy-pts[i].dy,dd=math.sqrt(dx*dx+dy*dy);if(dd<bd){bd=dd;best=i;}}if(best>=0)core(best);},child:CustomPaint(painter:_Constellation(center,pts,r),child:const SizedBox.expand()));}))])));}
}

class _Stars extends CustomPainter{const _Stars();@override void paint(Canvas c,Size s){final p=Paint()..color=Colors.white.withValues(alpha:.3);final r=math.Random(86);for(var i=0;i<130;i++){c.drawCircle(Offset(r.nextDouble()*s.width,r.nextDouble()*s.height),i%17==0?1.3:.7,p);}}@override bool shouldRepaint(covariant _Stars o)=>false;}
class _Logo extends CustomPainter{const _Logo();@override void paint(Canvas c,Size s){final m=Offset(s.width/2,s.height/2),g=Paint()..style=PaintingStyle.stroke..strokeWidth=2.3..color=const Color(0xffffb75b);c.drawCircle(m,29,g);final p=Path()..moveTo(m.dx-21,m.dy)..cubicTo(m.dx-12,m.dy-14,m.dx-2,m.dy-14,m.dx+7,m.dy)..cubicTo(m.dx+16,m.dy+14,m.dx+8,m.dy+14,m.dx,m.dy)..cubicTo(m.dx-8,m.dy-14,m.dx+2,m.dy-14,m.dx+11,m.dy)..cubicTo(m.dx+20,m.dy+14,m.dx+24,m.dy+8,m.dx+21,m.dy);c.drawPath(p,g);c.drawCircle(m+const Offset(11,0),3,Paint()..color=const Color(0xff58df8b));} @override bool shouldRepaint(covariant _Logo o)=>false;}

class _Constellation extends CustomPainter{final Offset center;final List<Offset> pts;final double r;const _Constellation(this.center,this.pts,this.r);@override void paint(Canvas c,Size s){final link=Paint()..style=PaintingStyle.stroke..strokeWidth=1..color=const Color(0xff4d7894).withValues(alpha:.24);for(final p in pts)c.drawLine(center,p,link);final orbit=Paint()..style=PaintingStyle.stroke..strokeWidth=1..color=const Color(0xff5b7f98).withValues(alpha:.18);c.drawOval(Rect.fromCenter(center:center,width:r*3.5,height:r*1.35),orbit);c.drawOval(Rect.fromCenter(center:center,width:r*2.9,height:r*.9),orbit);_yansi(c,center,r*.86);for(var i=0;i<5;i++)_core(c,pts[i],i,r*.34);}
  void _yansi(Canvas c,Offset o,double r){final glow=Paint()..shader=RadialGradient(colors:[const Color(0xff4ddcff).withValues(alpha:.65),const Color(0xff7d55ff).withValues(alpha:.25),Colors.transparent]).createShader(Rect.fromCircle(center:o,radius:r*1.5));c.drawCircle(o,r*1.5,glow);final gold=Paint()..style=PaintingStyle.stroke..strokeWidth=3..color=const Color(0xffffbd62),blue=Paint()..style=PaintingStyle.stroke..strokeWidth=4..color=const Color(0xff3ecbff);final p=Path()..moveTo(o.dx,o.dy+r)..cubicTo(o.dx-r*.95,o.dy+r*.05,o.dx-r*.55,o.dy-r*.95,o.dx,o.dy-r*.25)..cubicTo(o.dx+r*.55,o.dy-r*.95,o.dx+r*.95,o.dy+.05*r,o.dx,o.dy+r);c.drawPath(p,gold);c.drawArc(Rect.fromCircle(center:o,radius:r*.55),-2.1,4.1,false,blue);c.drawCircle(o,r*.22,Paint()..color=const Color(0xff6beaff));c.drawCircle(o,r*.11,Paint()..color=Colors.white);}
  void _core(Canvas c,Offset o,int i,double r){final col=_LifeOZMasterReferenceHomeState.colors[i],glow=Paint()..shader=RadialGradient(colors:[col.withValues(alpha:.55),col.withValues(alpha:.1),Colors.transparent]).createShader(Rect.fromCircle(center:o,radius:r*2));c.drawCircle(o,r*2,glow);final ring=Paint()..style=PaintingStyle.stroke..strokeWidth=2..color=col;c.drawOval(Rect.fromCenter(center:o,width:r*2.5,height:r*.7),ring);c.save();c.translate(o.dx,o.dy);c.rotate(i*.48);c.drawOval(Rect.fromCenter(center:Offset.zero,width:r*2.5,height:r*.7),ring);c.restore();final icon=Paint()..style=PaintingStyle.stroke..strokeWidth=2.7..strokeCap=StrokeCap.round..color=col;final p=Path();if(i==0){p.moveTo(o.dx,o.dy+r*.75);p.cubicTo(o.dx-r*.75,o.dy+.1*r,o.dx-r*.5,o.dy-r*.8,o.dx,o.dy-r*.2);p.cubicTo(o.dx+r*.5,o.dy-r*.8,o.dx+r*.75,o.dy+.1*r,o.dx,o.dy+r*.75);p.moveTo(o.dx,o.dy+r*.55);p.lineTo(o.dx,o.dy-r*.45);}else if(i==1){p.moveTo(o.dx,o.dy+r*.72);p.cubicTo(o.dx-r*.85,o.dy+.05*r,o.dx-r*.55,o.dy-r*.65,o.dx,o.dy-r*.18);p.cubicTo(o.dx+r*.55,o.dy-r*.65,o.dx+r*.85,o.dy+.05*r,o.dx,o.dy+r*.72);}else if(i==2){p.moveTo(o.dx-r*.55,o.dy+r*.45);for(var k=0;k<30;k++){final a=k/29*math.pi*2.8,rr=r*.55*(1-k/38);p.lineTo(o.dx+math.cos(a)*rr,o.dy+math.sin(a)*rr);}}else if(i==3){c.drawCircle(o,r*.55,icon);c.drawLine(o,Offset(o.dx,o.dy-r*.3),icon);c.drawLine(o,Offset(o.dx+r*.24,o.dy+r*.18),icon);}else{p.moveTo(o.dx,o.dy-r*.7);p.lineTo(o.dx+r*.48,o.dy);p.lineTo(o.dx,o.dy+r*.7);p.lineTo(o.dx-r*.48,o.dy);p.close();}if(i!=3)c.drawPath(p,icon);c.drawCircle(o,2.7,Paint()..color=Colors.white);}
  @override bool shouldRepaint(covariant _Constellation o)=>false;}
