import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'services/yansi_brain.dart';

class LifeOZFutureShell extends StatefulWidget {
  final SharedPreferences prefs;
  const LifeOZFutureShell({super.key, required this.prefs});
  @override State<LifeOZFutureShell> createState() => _LifeOZFutureShellState();
}

class _LifeOZFutureShellState extends State<LifeOZFutureShell> with SingleTickerProviderStateMixin {
  late final AnimationController _a;
  late final YansiBrain _brain;
  final FlutterTts _tts = FlutterTts();
  String _name=''; String _reality='OREON PRIME'; String _env='FOCUS'; String _message='';
  int _active=-1; bool _holo=false; bool _setup=false;
  final realities=['OREON PRIME','TERRA FLUX','VORTEX NEXUS','CRYSTA LUMEN','NEBULA SOUL','SHADOW CORE'];
  final envs=['MORNING','WORK','EVENING','FOCUS','REST'];
  final colors=[const Color(0xFF36E6A4),const Color(0xFFFF6675),const Color(0xFFFFC45A),const Color(0xFF4CCBFF),const Color(0xFFB77BFF)];

  @override void initState(){super.initState(); _a=AnimationController(vsync:this,duration:const Duration(seconds:16))..repeat(); _brain=YansiBrain(prefs:widget.prefs); _name=widget.prefs.getString('user_name')??''; _reality=widget.prefs.getString('lifeoz_reality')??'OREON PRIME'; _env=widget.prefs.getString('lifeoz_environment')??'FOCUS'; _setup=_name.isEmpty; _tts.setSpeechRate(.44);}
  @override void dispose(){_a.dispose();_tts.stop();super.dispose();}
  Future<void> _speak(String s) async {if(s.isEmpty)return; await _tts.stop(); await _tts.speak(s);}
  void _core(int i){setState(()=>_active=i); _speak(['This is your financial intelligence.','This is your life and growth intelligence.','This is your action and productivity intelligence.','This is your time and calendar intelligence.','This is your home and household intelligence.'][i]);}
  @override Widget build(BuildContext c)=>AnimatedBuilder(animation:_a,builder:(_,__)=>Scaffold(backgroundColor:const Color(0xFF01030A),body:SafeArea(child:_setup?_onboarding():_home())));

  Widget _onboarding()=>Stack(children:[const _Cosmos(),SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const SizedBox(height:20),const _Logo(),const SizedBox(height:34),const Text('YOUR LIFE.\nONE INTELLIGENCE.',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900,height:.98)),const SizedBox(height:10),const Text('Create your personal universe.',style:TextStyle(color:Colors.white54)),const SizedBox(height:26),TextField(onChanged:(v)=>_name=v,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(labelText:'YOUR NAME',labelStyle:TextStyle(color:Color(0xFF20D9FF)),border:OutlineInputBorder())),const SizedBox(height:18),const Text('VISUAL REALITY',style:TextStyle(color:Color(0xFF20D9FF),letterSpacing:2,fontSize:11)),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:realities.map((r)=>ChoiceChip(label:Text(r),selected:r==_reality,onSelected:(_){setState(()=>_reality=r);},selectedColor:const Color(0xFF20D9FF).withOpacity(.2))).toList()),const SizedBox(height:20),const Text('ADAPTIVE ENVIRONMENT',style:TextStyle(color:Colors.white60,letterSpacing:1.5,fontSize:11)),const SizedBox(height:8),Wrap(spacing:8,children:envs.map((e)=>ChoiceChip(label:Text(e),selected:e==_env,onSelected:(_){setState(()=>_env=e);},selectedColor:const Color(0xFFB77BFF).withOpacity(.2))).toList()),const SizedBox(height:28),SizedBox(width:double.infinity,height:56,child:FilledButton(onPressed:(){if(_name.trim().isEmpty)return;widget.prefs.setString('user_name',_name.trim());widget.prefs.setString('lifeoz_reality',_reality);widget.prefs.setString('lifeoz_environment',_env);setState(()=>_setup=false);_speak('Welcome, $_name. I am Yansi, your personal LifeOS intelligence.');},child:const Text('ENTER LIFEOZ',style:TextStyle(fontWeight:FontWeight.w900,letterSpacing:1.4))))]))]);

  Widget _home()=>Stack(children:[const _Cosmos(),Positioned(top:12,left:18,right:18,child:Row(children:[const _Logo(),const Spacer(),_circle(Icons.hub_rounded,()=>setState(()=>_holo=true))])),Positioned.fill(top:65,child:LayoutBuilder(builder:(_,s){final c=Offset(s.maxWidth/2,s.maxHeight*.45);final pts=[Offset(s.maxWidth*.22,s.maxHeight*.28),Offset(s.maxWidth*.78,s.maxHeight*.28),Offset(s.maxWidth*.16,s.maxHeight*.68),Offset(s.maxWidth*.84,s.maxHeight*.68),Offset(s.maxWidth*.5,s.maxHeight*.08)];return Stack(children:[CustomPaint(size:s.size,painter:_Network(_a.value,_active)),...pts.asMap().entries.map((e)=>Positioned(left:e.value.dx-48,top:e.value.dy-48,child:_node(e.key))),Positioned(left:c.dx-125,top:c.dy-125,child:GestureDetector(onTap:()=>setState(()=>_holo=true),child:CustomPaint(size:const Size(250,250),painter:_Yansi(_a.value,colors[_active<0?3:_active],_active>=0)))),Positioned(left:18,right:18,bottom:66,child:Column(children:[const Text('YANSI',style:TextStyle(fontSize:16,fontWeight:FontWeight.w900,letterSpacing:5)),Text('Your Silent Intelligence',style:TextStyle(color:colors[3],fontSize:11,letterSpacing:1.2)),if(_message.isNotEmpty)Text(_message,textAlign:TextAlign.center,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white70,fontSize:12))]))]);})),if(_holo)_hologram()]);

  Widget _node(int i)=>GestureDetector(onTap:()=>_core(i),child:CustomPaint(size:const Size(96,96),painter:_Symbol(i,colors[i],_active==i,_a.value)));
  Widget _circle(IconData icon,VoidCallback f)=>GestureDetector(onTap:f,child:Container(width:44,height:44,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:colors[3].withOpacity(.55)),color:Colors.white.withOpacity(.03)),child:Icon(icon,color:colors[3])));
  Widget _hologram()=>Positioned.fill(child:GestureDetector(onTap:()=>setState(()=>_holo=false),child:Container(color:Colors.black.withOpacity(.9),child:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Text('HOLOGRAPHIC CONTROL',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800,letterSpacing:2)),const SizedBox(height:24),Wrap(spacing:18,runSpacing:18,alignment:WrapAlignment.center,children:[_control('PROFILE',Icons.person),_control('DESIGN',Icons.auto_awesome),_control('PERMISSIONS',Icons.shield),_control('YANSI',Icons.psychology),_control('SETTINGS',Icons.tune)]),const SizedBox(height:28),const Text('Tap anywhere to close',style:TextStyle(color:Colors.white38,fontSize:10))])))));
  Widget _control(String n,IconData i)=>Column(children:[_circle(i,()=>_speak(n=='YANSI'?'I am Yansi. I listen, understand, organize, remind, protect and grow with you.':'$n control is ready.')),const SizedBox(height:4),Text(n,style:const TextStyle(color:Colors.white70,fontSize:9))]);
}

class _Logo extends StatelessWidget{const _Logo();@override Widget build(BuildContext c)=>Row(children:[Container(width:42,height:42,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:const Color(0xFF20D9FF),width:1.5),boxShadow:[BoxShadow(color:const Color(0xFF20D9FF),blurRadius:18)]),child:const Icon(Icons.all_inclusive,color:Color(0xFF20D9FF))),const SizedBox(width:9),const Text('LifeOZ',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,letterSpacing:2.8,fontSize:17))]);}
class _Cosmos extends StatelessWidget{const _Cosmos();@override Widget build(BuildContext c)=>Positioned.fill(child:CustomPaint(painter:_Bg()));}
class _Bg extends CustomPainter{@override void paint(Canvas x,Size s){x.drawRect(Offset.zero&s,Paint()..shader=const RadialGradient(colors:[Color(0xFF07182A),Color(0xFF01030A)],radius:1.1).createShader(Offset.zero&s));final r=math.Random(7);for(var i=0;i<90;i++){x.drawCircle(Offset(r.nextDouble()*s.width,r.nextDouble()*s.height),.5+r.nextDouble()*1.5,Paint()..color=(i.isEven?const Color(0xFF20D9FF):const Color(0xFFFFB84A)).withOpacity(.08));}final c=Offset(s.width/2,s.height*.45);for(var i=0;i<7;i++)x.drawOval(Rect.fromCenter(center:c,width:220+i*85.0,height:100+i*55.0),Paint()..style=PaintingStyle.stroke..strokeWidth:.7..color=const Color(0xFF20D9FF).withOpacity(.06));}@override bool shouldRepaint(covariant _Bg o)=>false;}
class _Network extends CustomPainter{final double p;final int a;_Network(this.p,this.a);@override void paint(Canvas x,Size s){final c=Offset(s.width/2,s.height*.45);final pts=[Offset(s.width*.22,s.height*.28),Offset(s.width*.78,s.height*.28),Offset(s.width*.16,s.height*.68),Offset(s.width*.84,s.height*.68),Offset(s.width*.5,s.height*.08)];for(var i=0;i<pts.length;i++){final q=pts[i];final col=i.isEven?const Color(0xFF20D9FF):const Color(0xFFFFB84A);final path=Path()..moveTo(q.dx,q.dy)..cubicTo(q.dx,q.dy+(c.dy-q.dy)*.25,c.dx,c.dy-(c.dy-q.dy)*.25,c.dx,c.dy);x.drawPath(path,Paint()..style=PaintingStyle.stroke..strokeWidth:i==a?2.2:1..color=col.withOpacity(i==a ? .65 : .2));}}@override bool shouldRepaint(covariant _Network o)=>true;}
class _Yansi extends CustomPainter{final double p;final Color col;final bool active;_Yansi(this.p,this.col,this.active);@override void paint(Canvas x,Size s){final c=Offset(s.width/2,s.height/2),z=s.shortestSide;for(var i=0;i<6;i++){final rr=z*(.23+i*.06);x.drawOval(Rect.fromCenter(center:c,width:rr*2,height:rr*1.45),Paint()..style=PaintingStyle.stroke..strokeWidth=i==2?1.8:.8..color=(i.isEven?const Color(0xFF20D9FF):const Color(0xFFFFB84A)).withOpacity(active ? .4 : .2));}x.drawCircle(c,z*.17,Paint()..shader=RadialGradient(colors:[Colors.white,col,const Color(0x00000000)]).createShader(Rect.fromCircle(center:c,radius:z*.17)));x.drawCircle(c,z*.05,Paint()..color=Colors.white..maskFilter=const MaskFilter.blur(BlurStyle.normal,10));}@override bool shouldRepaint(covariant _Yansi o)=>true;}
class _Symbol extends CustomPainter{final int i;final Color col;final bool active;final double p;_Symbol(this.i,this.col,this.active,this.p);@override void paint(Canvas x,Size s){final c=Offset(s.width/2,s.height/2),z=s.shortestSide;x.drawCircle(c,z*.31,Paint()..color=col.withOpacity(active ? .28 : .12)..maskFilter=MaskFilter.blur(BlurStyle.normal,active?18:10));x.drawOval(Rect.fromCenter(center:c,width:z*.8,height:z*.62),Paint()..style=PaintingStyle.stroke..strokeWidth=active?2:1..color=col.withOpacity(active ? .7 : .35));final q=Paint()..style=PaintingStyle.stroke..strokeWidth=2.3..strokeCap=StrokeCap.round..color=col;final path=Path();if(i==0){path.moveTo(c.dx,c.dy+z*.28);path.cubicTo(c.dx-z*.25,c.dy,c.dx-z*.2,c.dy-z*.25,c.dx,c.dy-z*.3);path.cubicTo(c.dx+z*.2,c.dy-z*.25,c.dx+z*.25,c.dy,c.dx,c.dy+z*.28);}else if(i==1){path.moveTo(c.dx,c.dy+z*.28);path.cubicTo(c.dx-z*.35,c.dy,c.dx-z*.25,c.dy-z*.3,c.dx,c.dy-z*.12);path.cubicTo(c.dx+z*.25,c.dy-z*.3,c.dx+z*.35,c.dy,c.dx,c.dy+z*.28);}else if(i==2){for(var n=0;n<70;n++){final t=n/69,a=t*math.pi*4.5,r=z*.28*(1-t),xx=c.dx+math.cos(a)*r,yy=c.dy+math.sin(a)*r;if(n==0)path.moveTo(xx,yy);else path.lineTo(xx,yy);}}else if(i==3){x.drawCircle(c,z*.2,q);x.drawOval(Rect.fromCenter(center:c,width:z*.72,height:z*.25),q);return;}else{path.moveTo(c.dx,c.dy-z*.3);path.lineTo(c.dx+z*.18,c.dy-z*.04);path.lineTo(c.dx+z*.12,c.dy+z*.25);path.lineTo(c.dx,c.dy+z*.3);path.lineTo(c.dx-z*.12,c.dy+z*.25);path.lineTo(c.dx-z*.18,c.dy-z*.04);path.close();}x.drawPath(path,q);x.drawCircle(c,z*.035,Paint()..color=Colors.white..maskFilter=const MaskFilter.blur(BlurStyle.normal,4));}@override bool shouldRepaint(covariant _Symbol o)=>true;}
