import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/yansi_brain.dart';
import '../services/core_router.dart';
import '../services/lifeos_permission_gate.dart';
import '../services/yansi_ambient_listener.dart';
import '../services/yansi_ambient_state_machine.dart';
import '../services/yansi_ambient_insight.dart';
import '../widgets/yansi_ambient_insight_card.dart';

class FuturisticHomeScreen extends StatefulWidget {
  final SharedPreferences prefs;
  final String userName, country, currency;
  final int themeIndex;
  final Future<void> Function(int index) onThemeChanged;
  const FuturisticHomeScreen({super.key, required this.prefs, required this.userName, required this.country, required this.currency, required this.themeIndex, required this.onThemeChanged});
  @override State<FuturisticHomeScreen> createState()=>_FuturisticHomeScreenState();
}
class _FuturisticHomeScreenState extends State<FuturisticHomeScreen> with SingleTickerProviderStateMixin {
  late final AnimationController _a=AnimationController(vsync:this,duration:const Duration(seconds:7))..repeat();
  final FlutterTts _tts=FlutterTts();
  late final YansiAmbientStateMachine _yansiState;
  late final YansiAmbientListener _ambient;
  late int _theme; bool _menu=false; String _state='IDLE'; YansiAmbientInsight? _insight;
  @override void initState(){super.initState();_theme=widget.themeIndex;_yansiState=YansiAmbientStateMachine();_yansiState.addListener(_syncYansiState);_ambient=YansiAmbientListener(permissions:LifeOSPermissionGate(widget.prefs),state:_yansiState,onUtterance:_ask);WidgetsBinding.instance.addPostFrameCallback((_) async {await _welcome();if(widget.prefs.getBool('permission_voice')==true) await _ambient.start();});}
  void _syncYansiState(){if(!mounted)return;final s=_yansiState.state.name.toUpperCase();if(_state!=s)setState(()=>_state=s);}
  @override void dispose(){_ambient.dispose();_yansiState.removeListener(_syncYansiState);_yansiState.dispose();_a.dispose();_tts.stop();super.dispose();}
  Future<void> _welcome() async{if(widget.prefs.getBool('permission_voice')!=true)return;await Future.delayed(const Duration(milliseconds:700));final n=widget.userName.trim();await _speak(n.isEmpty?'Welcome. I am Yansi, your personal LifeOS AI agent. I am here whenever you need me.':'Welcome, $n. I am Yansi, your personal LifeOS AI agent. I am here whenever you need me.');}
  Future<void> _speak(String text) async{if(!mounted||widget.prefs.getBool('permission_voice')!=true)return;_yansiState.setSpeaking();try{await _tts.setLanguage('en-IN');await _tts.setSpeechRate(.46);await _tts.speak(text);}catch(_){ }if(mounted)_yansiState.setIdle();}
  Future<void> _ask(String text) async{if(text.trim().isEmpty)return;_yansiState.setThinking(text);try{final r=await YansiBrain(prefs:widget.prefs).process(text);if(!mounted)return;_yansiState.setActing();await _speak(r.response);await widget.prefs.setString('last_yansi_voice_text',text);await widget.prefs.setString('last_yansi_response',r.response);}catch(_){await _speak('I am connecting that intelligence now.');}}
  Future<void> _loadInsight() async { final insight=await YansiAmbientInsightService(prefs:widget.prefs).prepare(); if(!mounted)return; setState(()=>_insight=insight); }
  void _core(BuildContext c,int i)=>CoreRouter.open(c,i,widget.currency);
  @override Widget build(BuildContext context){final c=_colors(_theme);return Scaffold(backgroundColor:c.bg,body:Stack(children:[Positioned.fill(child:AnimatedBuilder(animation:_a,builder:(_,__)=>CustomPaint(painter:_Neural(p:_a.value,one:c.p,two:c.s)))),SafeArea(child:Padding(padding:const EdgeInsets.all(10),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[_icon(Icons.menu_rounded,c,()=>setState(()=>_menu=!_menu)),_chip(c),_icon(Icons.notifications_none_rounded,c,()=>_loadInsight())]))),Positioned(top:78,left:20,right:20,child:Column(children:[Text(widget.userName.isEmpty?'LIFEOS':widget.userName.toUpperCase(),style:TextStyle(color:c.t,fontSize:12,letterSpacing:3)),const SizedBox(height:5),Text('PERSONAL INTELLIGENCE ENVIRONMENT',style:TextStyle(color:c.m,fontSize:8,letterSpacing:2))])),Positioned(top:MediaQuery.of(context).size.height*.19,left:0,right:0,child:AnimatedBuilder(animation:_a,builder:(_,__)=>_Yansi(p:_a.value,state:_state,one:c.p,two:c.s))),if(_insight!=null)Positioned(top:MediaQuery.of(context).size.height*.39,left:16,right:16,child:YansiAmbientInsightCard(insight:_insight!,onDismiss:()=>setState(()=>_insight=null),onAction:()=>setState(()=>_insight=null))),Positioned.fill(top:MediaQuery.of(context).size.height*.48,bottom:70,child:Stack(children:[_coreIcon(context,0,Icons.account_balance_wallet_outlined,.12,.02,c),_coreIcon(context,1,Icons.auto_awesome_outlined,.68,.02,c),_coreIcon(context,2,Icons.bolt_outlined,.04,.43,c),_coreIcon(context,3,Icons.home_work_outlined,.76,.43,c),_coreIcon(context,4,Icons.timeline_rounded,.43,.70,c)])),if(_menu)Positioned(top:58,left:10,child:_panel(c))]));}
  Widget _icon(IconData i,_C c,VoidCallback f)=>GestureDetector(onTap:f,child:Container(width:36,height:36,decoration:BoxDecoration(shape:BoxShape.circle,color:c.t.withOpacity(.035),border:Border.all(color:c.t.withOpacity(.1))),child:Icon(i,size:18,color:c.t.withOpacity(.72))));
  Widget _chip(_C c)=>AnimatedContainer(duration:const Duration(milliseconds:300),padding:const EdgeInsets.symmetric(horizontal:12,vertical:6),decoration:BoxDecoration(borderRadius:BorderRadius.circular(20),border:Border.all(color:c.p.withOpacity(.22))),child:Text(_state,style:TextStyle(color:c.p,fontSize:8,letterSpacing:2)));
  Widget _coreIcon(BuildContext x,int i,IconData icon,double l,double t,_C c)=>Positioned(left:MediaQuery.of(x).size.width*l,top:MediaQuery.of(x).size.height*t,child:GestureDetector(onTap:()=>_core(x,i),child:Container(width:62,height:62,decoration:BoxDecoration(shape:BoxShape.circle,color:c.bg.withOpacity(.72),border:Border.all(color:c.p.withOpacity(.45)),boxShadow:[BoxShadow(color:c.p.withOpacity(.16),blurRadius:25)]),child:Icon(icon,size:24,color:c.p))));
  Widget _panel(_C c)=>Container(width:235,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:c.bg.withOpacity(.97),borderRadius:BorderRadius.circular(20),border:Border.all(color:c.p.withOpacity(.25))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('LIFEOS WORLDS',style:TextStyle(color:c.p,fontSize:9,letterSpacing:2)),const SizedBox(height:8),...List.generate(5,(i)=>GestureDetector(onTap:()async{setState(()=>_theme=i);await widget.onThemeChanged(i);setState(()=>_menu=false);},child:Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Text(const ['Aurora Nexus','Void Matrix','Quantum Purple','Solaris Prime','Frost Minimal'][i],style:TextStyle(color:i==_theme?c.p:c.t,fontSize:11)))))]));
  _C _colors(int i){const z=[_C(Color(0xFF020B0B),Color(0xFF00FFD5),Color(0xFF35FF72),Color(0xFFE9FFFF),Color(0xFF83AAA7)),_C(Color(0xFF020611),Color(0xFF168CFF),Color(0xFF52C7FF),Color(0xFFEAF5FF),Color(0xFF7690A8)),_C(Color(0xFF0A0310),Color(0xFFD24CFF),Color(0xFFFF54C8),Color(0xFFFFEEFF),Color(0xFFA98EAE)),_C(Color(0xFF0B0802),Color(0xFFFFC928),Color(0xFFFF8A00),Color(0xFFFFF7D9),Color(0xFFAA9866)),_C(Color(0xFFF4FAFF),Color(0xFF147BFF),Color(0xFF5AC8FF),Color(0xFF08244A),Color(0xFF68819B))];return z[i.clamp(0,4)];}
}
class _C{final Color bg,p,s,t,m;const _C(this.bg,this.p,this.s,this.t,this.m);}
class _Yansi extends StatelessWidget{final double p;final String state;final Color one,two;const _Yansi({required this.p,required this.state,required this.one,required this.two});@override Widget build(BuildContext c){final q=1+math.sin(p*math.pi*2)*.07;return Center(child:Transform.scale(scale:q,child:Stack(alignment:Alignment.center,children:[for(int i=0;i<4;i++)Container(width:120+i*34,height:120+i*34,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:one.withOpacity(.12+i*.035)))),Container(width:92,height:92,decoration:BoxDecoration(shape:BoxShape.circle,gradient:RadialGradient(colors:[one.withOpacity(.5),two.withOpacity(.18),Colors.transparent]),boxShadow:[BoxShadow(color:one.withOpacity(.35),blurRadius:45)])),Icon(Icons.auto_awesome,size:30,color:Colors.white.withOpacity(.9)),Positioned(bottom:-18,child:Text(state,style:TextStyle(color:one,fontSize:8,letterSpacing:2)))])));}}
class _Neural extends CustomPainter{final double p;final Color one,two;_Neural({required this.p,required this.one,required this.two});@override void paint(Canvas c,Size s){final q=Paint()..style=PaintingStyle.stroke..strokeWidth=1;final o=Offset(s.width/2,s.height*.36);for(int i=0;i<18;i++){final a=p*math.pi*2+i*.8,r=s.width*(.18+(i%5)*.045),e=o+Offset(math.cos(a)*r,math.sin(a)*r);q.color=Color.lerp(one,two,(i%7)/7)!.withOpacity(.045);c.drawLine(o,e,q);c.drawCircle(e,1.5,q);}}@override bool shouldRepaint(covariant _Neural x)=>x.p!=p||x.one!=one||x.two!=two;}
